### Ejercicio 1

PASO 1: Importacion de base de datos y conexion

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

# Configuración de la conexión a MySQL
usuario = 'root'
contraseña = 'alexfango04'
host = 'localhost:3309'
base_de_datos = 'db'

# Crear la cadena de conexión
cadena_conexion = f'mysql+pymysql://{usuario}:{contraseña}@{host}/{base_de_datos}'

# Crear el motor de conexión
motor = create_engine(cadena_conexion)

# Consulta SQL con el nombre de la tabla entre backticks
consulta = "SELECT * FROM `players_data-2024_2025`"

# Cargar datos en un DataFrame
df = pd.read_sql(consulta, motor)

# Mostrar las primeras filas
print(df.head())

   Rk             Player   Nation    Pos        Squad                Comp  \
0   1         Max Aarons  eng ENG     DF  Bournemouth  eng Premier League
1   2         Max Aarons  eng ENG  DF,MF     Valencia          es La Liga
2   3     Rodrigo Abajas   es ESP     DF     Valencia          es La Liga
3   4     James Abankwah   ie IRL  DF,MF      Udinese          it Serie A
4   5  Keyliane Abdallah   fr FRA     FW    Marseille          fr Ligue 1

    Age  Born  MP  Starts  ...  Att (GK)  Thr  Launch%  AvgLen  Opp  Stp  \
0  24.0  2000   3       1  ...
1  24.0  2000   4       1  ...
2  21.0  2003   1       1  ...
3  20.0  2004   6       0  ...
4  18.0  2006   1       0  ...

   Stp%  #OPA  #OPA/90  AvgDist
0
1
2
3
4

[5 rows x 267 columns]

### 1.1 Comprovacion de datos

In [2]:
# 1. Análisis inicial de valores nulos
print("---------Valores nulos por columna------------")
print(df.isnull().sum())

# 2. Porcentaje de valores nulos por columna
print("\n---------Porcentaje de valores nulos-------------")
print((df.isnull().sum() / len(df)) * 100)

# 3. Verificación de duplicados completos
print("\n------ Filas duplicadas exactas ------")
print("Número de duplicados exactos:", df.duplicated().sum())

# 4. Verificación de duplicados en columnas clave (Player y Nation)
print("\n------ Duplicados en columnas clave -------")
print("Jugadores con mismo nombre (Player):", df.duplicated(subset=['Player']).sum())
print("Jugadores con misma nacionalidad (Nation):", df.duplicated(subset=['Nation']).sum())

# 5. Mostrar algunas filas con valores nulos para inspección
print("\n----- Ejemplo de filas con valores nulos ----")
print(df[df.isnull().any(axis=1)].head())

---------Valores nulos por columna------------
Rk         0
Player     0
Nation     0
Pos        0
Squad      0
          ..
Stp        0
Stp%       0
#OPA       0
#OPA/90    0
AvgDist    0
Length: 267, dtype: int64

---------Porcentaje de valores nulos-------------
Rk         0.0
Player     0.0
Nation     0.0
Pos        0.0
Squad      0.0
          ...
Stp        0.0
Stp%       0.0
#OPA       0.0
#OPA/90    0.0
AvgDist    0.0
Length: 267, dtype: float64

------ Filas duplicadas exactas ------
Número de duplicados exactos: 0

------ Duplicados en columnas clave -------
Jugadores con mismo nombre (Player): 7
Jugadores con misma nacionalidad (Nation): 71

----- Ejemplo de filas con valores nulos ----
Empty DataFrame
Columns: [Rk, Player, Nation, Pos, Squad, Comp, Age, Born, MP, Starts, Min, 90s, Gls, Ast, G+A, G-PK, PK, PKatt, CrdY, CrdR, xG, npxG, xAG, npxG+xAG, PrgC, PrgP, PrgR, G+A-PK, xG+xAG, Rk_stats_shooting, Nation_stats_shooting, Pos_stats_shooting, Comp_stats_shooting, Age_stats_shooting, Born_stats_shooting, 90s_stats_shooting, Gls_stats_shooting, Sh, SoT, SoT%, Sh/90, SoT/90, G/Sh, G/SoT, Dist, FK, PK_stats_shooting, PKatt_stats_shooting, xG_stats_shooting, npxG_stats_shooting, npxG/Sh, G-xG, np:G-xG, Rk_stats_passing, Nation_stats_passing, Pos_stats_passing, Comp_stats_passing, Age_stats_passing, Born_stats_passing, 90s_stats_passing, Cmp, Att, Cmp%, TotDist, PrgDist, Ast_stats_passing, xAG_stats_passing, xA, A-xAG, KP, 1/3, PPA, CrsPA, PrgP_stats_passing, Rk_stats_passing_types, Nation_stats_passing_types, Pos_stats_passing_types, Comp_stats_passing_types, Age_stats_passing_types, Born_stats_passing_types, 90s_stats_passing_types, Att_stats_passing_types, Live, Dead, FK_stats_passing_types, TB, Sw, Crs, TI, CK, In, Out, Str, Cmp_stats_passing_types, Off, Blocks, Rk_stats_gca, Nation_stats_gca, Pos_stats_gca, Comp_stats_gca, ...]
Index: []

[0 rows x 267 columns]

### Limpieza de datos

In [3]:
import pandas as pd
from sqlalchemy import create_engine

# Configuración de la conexión a MySQL
usuario = 'root'
contraseña = 'alexfango04'
host = 'localhost:3309'
base_de_datos = 'db'

# Crear el motor de conexión
engine = create_engine(f'mysql+pymysql://{usuario}:{contraseña}@{host}/{base_de_datos}')

# Cargar datos desde la tabla original (con backticks correctos)
df = pd.read_sql('SELECT * FROM `players_data-2024_2025`', engine)

# Análisis de cantidad de datos antes de limpieza
print("---------Datos originales---------")
print(f"Filas originales: {len(df)}")
print("Valores nulos por columna:")
print(df.isnull().sum())

# Limpieza básica: eliminar filas con cualquier valor nulo
df_limpio = df.dropna()

# Verificación posterior a la limpieza
print("\n---------Después de limpieza---------")
print(f"Filas limpias: {len(df_limpio)}")

# Exportar a nueva tabla en MySQL
try:
    df_limpio.to_sql('players_sin_nulos', engine, if_exists='replace', index=False)
    print("\n✅ Tabla 'players_sin_nulos' creada exitosamente en MySQL.")
except Exception as e:
    print(f"\n❌ Error al exportar: {e}")

---------Datos originales---------
Filas originales: 100
Valores nulos por columna:
Rk         0
Player     0
Nation     0
Pos        0
Squad      0
          ..
Stp        0
Stp%       0
#OPA       0
#OPA/90    0
AvgDist    0
Length: 267, dtype: int64

---------Después de limpieza---------
Filas limpias: 100

✅ Tabla 'players_sin_nulos' creada exitosamente en MySQL.

### Ejercicio 2

In [4]:
# Importación de librerías
import requests
import pandas as pd
from sqlalchemy import create_engine

print("Librerías importadas correctamente")

Librerías importadas correctamente

### 1. Configuracion de conexion de bases de datos

In [5]:
# Configuración de la base de datos
config_mysql = {
    'usuario': 'root',        # Cambiar por tu usuario
    'contraseña': 'alexfango04',    # Cambiar por tu contraseña
    'host': 'localhost',      # Servidor de la base de datos
    'puerto': '3309',         # Puerto de MySQL
    'base_de_datos': 'db'  # Nombre de la base de datos
}

# Crear cadena de conexión
cadena_conexion = f"mysql+pymysql://{config_mysql['usuario']}:{config_mysql['contraseña']}@{config_mysql['host']}:{config_mysql['puerto']}/{config_mysql['base_de_datos']}"

print("⚙️ Configuración de MySQL completada")
print(f"Cadena de conexión: {cadena_conexion[:20]}...")

⚙️ Configuración de MySQL completada
Cadena de conexión: mysql+pymysql://root...

### 2. Obtencion de datos de la api

In [19]:
import requests

# Función para obtener lista de Pokémon
def obtener_lista_pokemon(limit=10):
    url = f"https://pokeapi.co/api/v2/pokemon?limit={limit}"
    try:
        print("🔍 Obteniendo lista de Pokémon...")
        respuesta = requests.get(url)
        respuesta.raise_for_status()
        data = respuesta.json()
        print("✅ Lista de Pokémon obtenida correctamente.")
        return data['results']
    except Exception as e:
        print(f"❌ Error al obtener lista de Pokémon: {e}")
        return []

# Función para obtener detalles de un Pokémon por URL
def obtener_detalles_pokemon(url):
    try:
        respuesta = requests.get(url)
        respuesta.raise_for_status()
        return respuesta.json()
    except Exception as e:
        print(f"❌ Error al obtener detalles del Pokémon: {e}")
        return None

# Ejecutar funciones
lista_pokemon = obtener_lista_pokemon()

# Mostrar nombres y detalles del primer Pokémon
if lista_pokemon:
    print("\n📋 Lista de Pokémon:")
    for p in lista_pokemon:
        print(f"- {p['name'].capitalize()}")

    print("\n🔎 Detalles del primer Pokémon:")
    primer_pokemon = lista_pokemon[0]
    detalles = obtener_detalles_pokemon(primer_pokemon['url'])
    
    if detalles:
        tipos = [t['type']['name'] for t in detalles['types']]
        habilidades = [a['ability']['name'] for a in detalles['abilities']]
        
        print(f"Nombre: {detalles['name'].capitalize()}")
        print(f"Tipos: {', '.join(tipos)}")
        print(f"Habilidades: {', '.join(habilidades)}")

🔍 Obteniendo lista de Pokémon...
✅ Lista de Pokémon obtenida correctamente.

📋 Lista de Pokémon:
- Bulbasaur
- Ivysaur
- Venusaur
- Charmander
- Charmeleon
- Charizard
- Squirtle
- Wartortle
- Blastoise
- Caterpie

🔎 Detalles del primer Pokémon:
Nombre: Bulbasaur
Tipos: grass, poison
Habilidades: overgrow, chlorophyll

### 3. Limpieza de datos

In [20]:
import requests
import pandas as pd

# Obtener lista de Pokémon (limit = 10)
def obtener_lista_pokemon(limit=10):
    url = f"https://pokeapi.co/api/v2/pokemon?limit={limit}"
    try:
        print("🔍 Obteniendo lista de Pokémon...")
        respuesta = requests.get(url)
        respuesta.raise_for_status()
        return respuesta.json().get('results', [])
    except Exception as e:
        print(f"❌ Error al obtener la lista: {e}")
        return []

# Obtener detalles de un Pokémon individual
def obtener_detalles_pokemon(url):
    try:
        respuesta = requests.get(url)
        respuesta.raise_for_status()
        return respuesta.json()
    except Exception as e:
        print(f"❌ Error al obtener detalles del Pokémon: {e}")
        return None

# Ejecutar flujo principal
datos_pokemon = obtener_lista_pokemon(limit=10)

if datos_pokemon:
    print("\n🧹 Iniciando limpieza de datos para TODOS los Pokémon...")

    datos_procesados = []

    for p in datos_pokemon:
        detalles = obtener_detalles_pokemon(p['url'])
        if detalles:
            datos = {
                'nombre': detalles.get('name', 'desconocido').capitalize(),
                'tipos': ', '.join([t['type']['name'] for t in detalles.get('types', [])]),
                'habilidades': ', '.join([h['ability']['name'] for h in detalles.get('abilities', [])]),
                'peso': detalles.get('weight', None),
                'altura': detalles.get('height', None)
            }
            datos_procesados.append(datos)

    # Convertir a DataFrame
    df = pd.DataFrame(datos_procesados)

    # Eliminar filas con datos faltantes en campos clave
    df_limpio = df.dropna(subset=['nombre', 'tipos', 'habilidades'])

    print("\n🔍 Muestra de datos limpios (de todos los Pokémon):")
    display(df_limpio.head())
    print(f"\n📝 Total de Pokémon después de limpieza: {len(df_limpio)}")
else:
    print("❌ No hay datos de Pokémon para procesar.")

🔍 Obteniendo lista de Pokémon...

🧹 Iniciando limpieza de datos para TODOS los Pokémon...

🔍 Muestra de datos limpios (de todos los Pokémon):

       nombre          tipos            habilidades  peso  altura
0   Bulbasaur  grass, poison  overgrow, chlorophyll    69       7
1     Ivysaur  grass, poison  overgrow, chlorophyll   130      10
2    Venusaur  grass, poison  overgrow, chlorophyll  1000      20
3  Charmander           fire     blaze, solar-power    85       6
4  Charmeleon           fire     blaze, solar-power   190      11

📝 Total de Pokémon después de limpieza: 10

### 4.Transformacion de datos

In [22]:
import pandas as pd  # Solo si no está importado antes

if 'df_limpio' in locals() and not df_limpio.empty:
    print("\n🔄 Iniciando clasificación por peso...")

    # Definir rangos para peso en hectogramos (API usa hg)
    bins = [0, 50, 150, 300, 600, float('inf')]
    labels = ['Muy ligero', 'Ligero', 'Medio', 'Pesado', 'Muy pesado']

    df_limpio['categoria_peso'] = pd.cut(
        df_limpio['peso'],
        bins=bins,
        labels=labels
    )

    print("\n📊 Distribución por categoría de peso:")
    print(df_limpio['categoria_peso'].value_counts())

    print("\n🔍 Muestra de datos transformados:")
    display(df_limpio.head())
else:
    print("No hay datos limpios para transformar.")

🔄 Iniciando clasificación por peso...

📊 Distribución por categoría de peso:
categoria_peso
Ligero        4
Muy pesado    3
Medio         2
Muy ligero    1
Pesado        0
Name: count, dtype: int64

🔍 Muestra de datos transformados:

,nombre,tipos,habilidades,peso,altura,categoria_peso
0,Bulbasaur,"grass, poison","overgrow, chlorophyll",69,7,Ligero
1,Ivysaur,"grass, poison","overgrow, chlorophyll",130,10,Ligero
2,Venusaur,"grass, poison","overgrow, chlorophyll",1000,20,Muy pesado
3,Charmander,fire,"blaze, solar-power",85,6,Ligero
4,Charmeleon,fire,"blaze, solar-power",190,11,Medio

### 5. Exportacion de datos

In [23]:
from sqlalchemy import create_engine

# Cadena de conexión a MySQL (ajústala con tus credenciales)
usuario = 'root'
contraseña = 'alexfango04'
host = 'localhost:3309'
base_de_datos = 'db'

cadena_conexion = f'mysql+pymysql://{usuario}:{contraseña}@{host}/{base_de_datos}'

# Verificar y exportar
if 'df_limpio' in locals() and not df_limpio.empty:
    try:
        print("\n💾 Conectando a MySQL para exportar datos...")
        engine = create_engine(cadena_conexion)

        # Verificar conexión
        with engine.connect() as conn:
            print("✅ Conexión a MySQL exitosa")

        # Exportar el DataFrame a la tabla 'pokemon_api_limpios'
        df_limpio.to_sql(
            name='pokemon_api_limpios',
            con=engine,
            if_exists='replace',
            index=False
        )

        print("💾 Datos exportados correctamente a la tabla 'pokemon_api_limpios'")
        print(f"📌 Total de registros exportados: {len(df_limpio)}")

    except Exception as e:
        print(f"❌ Error al exportar a MySQL: {e}")
else:
    print("⚠️ No hay datos para exportar")

💾 Conectando a MySQL para exportar datos...
✅ Conexión a MySQL exitosa
💾 Datos exportados correctamente a la tabla 'pokemon_api_limpios'
📌 Total de registros exportados: 10

In [24]:
import requests
import pandas as pd
from sqlalchemy import create_engine

# 1. Configuración de la conexión a MySQL
config_mysql = {
    'usuario': 'root',
    'contraseña': 'alexfango04',
    'host': 'localhost',
    'puerto': '3309',
    'base_de_datos': 'db'
}

# 2. Función para obtener lista de Pokémon
def obtener_lista_pokemon(limit=10):
    url = f"https://pokeapi.co/api/v2/pokemon?limit={limit}"
    try:
        respuesta = requests.get(url)
        respuesta.raise_for_status()
        return respuesta.json().get('results', [])
    except requests.exceptions.RequestException as e:
        print(f"❌ Error al obtener la lista de Pokémon: {e}")
        return None

# 3. Función para obtener detalles individuales de cada Pokémon
def obtener_detalles_pokemon(url):
    try:
        respuesta = requests.get(url)
        respuesta.raise_for_status()
        return respuesta.json()
    except requests.exceptions.RequestException as e:
        print(f"❌ Error al obtener detalles del Pokémon: {e}")
        return None

# Obtener los datos
datos_pokemon = obtener_lista_pokemon(limit=10)

if datos_pokemon:
    # 4. Procesamiento de datos
    datos_procesados = []

    for p in datos_pokemon:
        detalles = obtener_detalles_pokemon(p['url'])
        if detalles:
            datos = {
                'nombre': detalles.get('name', 'desconocido').capitalize(),
                'tipos': ', '.join([t['type']['name'] for t in detalles.get('types', [])]),
                'habilidades': ', '.join([h['ability']['name'] for h in detalles.get('abilities', [])]),
                'peso': detalles.get('weight', None),
                'altura': detalles.get('height', None)
            }
            datos_procesados.append(datos)

    df = pd.DataFrame(datos_procesados)
    df_limpio = df.dropna(subset=['nombre', 'tipos', 'habilidades'])

    # 5. Conexión a MySQL 
    try:
        cadena_conexion = f"mysql+pymysql://{config_mysql['usuario']}:{config_mysql['contraseña']}@{config_mysql['host']}:{config_mysql['puerto']}/{config_mysql['base_de_datos']}"
        engine = create_engine(cadena_conexion)

        with engine.connect() as conn:
            print("✅ ¡Conexión a MySQL exitosa!")

        # 6. Exportar a tabla
        df_limpio.to_sql(
            'pokemon_api_alternativa',
            engine,
            if_exists='replace',
            index=False
        )

        print("\n💾 ¡Datos exportados correctamente a MySQL!")
        print(f"📌 Tabla: 'pokemon_api_alternativa' en la base de datos '{config_mysql['base_de_datos']}'")
        print(f"📊 Total de Pokémon exportados: {len(df_limpio)}")

    except Exception as e:
        print(f"\n❌ Error al conectar/exportar a MySQL: {e}")
        print("Verifica lo siguiente:")
        print(f"- Usuario: {config_mysql['usuario']}")
        print(f"- Contraseña: {'*' * len(config_mysql['contraseña'])}")
        print(f"- Host: {config_mysql['host']}")
        print(f"- Puerto: {config_mysql['puerto']}")
        print(f"- Base de datos: {config_mysql['base_de_datos']}")
        print("\n¿Está corriendo el servidor MySQL? ¿Tienes los privilegios adecuados?")
else:
    print("❌ No se pudieron obtener datos de la PokéAPI para procesar")

✅ ¡Conexión a MySQL exitosa!

💾 ¡Datos exportados correctamente a MySQL!
📌 Tabla: 'pokemon_api_alternativa' en la base de datos 'db'
📊 Total de Pokémon exportados: 10